-- Breadcrumb preferences table
CREATE TABLE IF NOT EXISTS breadcrumb_preferences (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL UNIQUE,
  show_icons BOOLEAN DEFAULT TRUE NOT NULL,
  compact_mode BOOLEAN DEFAULT FALSE NOT NULL,
  hide_on_mobile BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
