/**
 * Comprehensive vocabulary database for multiple languages
 * Maps words to their proficiency levels (HSK, CEFR, JLPT, TOPIK)
 * 
 * This database contains curated high-frequency words for each language.
 * For comprehensive coverage, the system can be extended with external APIs.
 */

interface VocabEntry {
  level: number;
  frequency: string;
}

// Chinese HSK Vocabulary Database - 1000+ curated words
export const chineseHSKDatabase: Record<string, VocabEntry> = {
  // HSK 1 - Essential basics (150 words)
  "我": { level: 1, frequency: "Very Common" },
  "你": { level: 1, frequency: "Very Common" },
  "他": { level: 1, frequency: "Very Common" },
  "她": { level: 1, frequency: "Very Common" },
  "的": { level: 1, frequency: "Very Common" },
  "是": { level: 1, frequency: "Very Common" },
  "不": { level: 1, frequency: "Very Common" },
  "了": { level: 1, frequency: "Very Common" },
  "在": { level: 1, frequency: "Very Common" },
  "有": { level: 1, frequency: "Very Common" },
  "人": { level: 1, frequency: "Very Common" },
  "这": { level: 1, frequency: "Very Common" },
  "中": { level: 1, frequency: "Very Common" },
  "大": { level: 1, frequency: "Very Common" },
  "来": { level: 1, frequency: "Very Common" },
  "上": { level: 1, frequency: "Very Common" },
  "国": { level: 1, frequency: "Very Common" },
  "个": { level: 1, frequency: "Very Common" },
  "到": { level: 1, frequency: "Very Common" },
  "说": { level: 1, frequency: "Very Common" },
  "们": { level: 1, frequency: "Very Common" },
  "为": { level: 1, frequency: "Very Common" },
  "子": { level: 1, frequency: "Very Common" },
  "和": { level: 1, frequency: "Very Common" },
  "你好": { level: 1, frequency: "Very Common" },
  "谢谢": { level: 1, frequency: "Very Common" },
  "再见": { level: 1, frequency: "Very Common" },
  "对不起": { level: 1, frequency: "Very Common" },
  "没关系": { level: 1, frequency: "Very Common" },
  "什么": { level: 1, frequency: "Very Common" },
  "谁": { level: 1, frequency: "Very Common" },
  "哪": { level: 1, frequency: "Very Common" },
  "怎么": { level: 1, frequency: "Very Common" },
  "多少": { level: 1, frequency: "Very Common" },
  "几": { level: 1, frequency: "Very Common" },
  "吗": { level: 1, frequency: "Very Common" },
  "呢": { level: 1, frequency: "Very Common" },
  "吧": { level: 1, frequency: "Very Common" },
  "一": { level: 1, frequency: "Very Common" },
  "二": { level: 1, frequency: "Very Common" },
  "三": { level: 1, frequency: "Very Common" },
  "四": { level: 1, frequency: "Very Common" },
  "五": { level: 1, frequency: "Very Common" },
  "六": { level: 1, frequency: "Very Common" },
  "七": { level: 1, frequency: "Very Common" },
  "八": { level: 1, frequency: "Very Common" },
  "九": { level: 1, frequency: "Very Common" },
  "十": { level: 1, frequency: "Very Common" },
  "年": { level: 1, frequency: "Very Common" },
  "月": { level: 1, frequency: "Very Common" },
  "日": { level: 1, frequency: "Very Common" },
  "今天": { level: 1, frequency: "Very Common" },
  "明天": { level: 1, frequency: "Very Common" },
  "昨天": { level: 1, frequency: "Very Common" },
  "现在": { level: 1, frequency: "Very Common" },
  "时候": { level: 1, frequency: "Very Common" },
  "爸爸": { level: 1, frequency: "Very Common" },
  "妈妈": { level: 1, frequency: "Very Common" },
  "老师": { level: 1, frequency: "Very Common" },
  "学生": { level: 1, frequency: "Very Common" },
  "朋友": { level: 1, frequency: "Very Common" },
  "家": { level: 1, frequency: "Very Common" },
  "学校": { level: 1, frequency: "Very Common" },
  "中国": { level: 1, frequency: "Very Common" },
  "汉语": { level: 1, frequency: "Very Common" },
  "书": { level: 1, frequency: "Very Common" },
  "水": { level: 1, frequency: "Very Common" },
  "茶": { level: 1, frequency: "Very Common" },
  "米饭": { level: 1, frequency: "Very Common" },
  "钱": { level: 1, frequency: "Very Common" },
  "衣服": { level: 1, frequency: "Very Common" },
  "看": { level: 1, frequency: "Very Common" },
  "听": { level: 1, frequency: "Very Common" },
  "读": { level: 1, frequency: "Very Common" },
  "写": { level: 1, frequency: "Very Common" },
  "吃": { level: 1, frequency: "Very Common" },
  "喝": { level: 1, frequency: "Very Common" },
  "买": { level: 1, frequency: "Very Common" },
  "去": { level: 1, frequency: "Very Common" },
  "做": { level: 1, frequency: "Very Common" },
  "坐": { level: 1, frequency: "Very Common" },
  "住": { level: 1, frequency: "Very Common" },
  "学": { level: 1, frequency: "Very Common" },
  "工作": { level: 1, frequency: "Very Common" },
  "喜欢": { level: 1, frequency: "Very Common" },
  "想": { level: 1, frequency: "Very Common" },
  "爱": { level: 1, frequency: "Very Common" },
  "能": { level: 1, frequency: "Very Common" },
  "会": { level: 1, frequency: "Very Common" },
  "好": { level: 1, frequency: "Very Common" },
  "小": { level: 1, frequency: "Very Common" },
  "多": { level: 1, frequency: "Very Common" },
  "少": { level: 1, frequency: "Very Common" },
  "冷": { level: 1, frequency: "Very Common" },
  "热": { level: 1, frequency: "Very Common" },
  "高兴": { level: 1, frequency: "Very Common" },
  "漂亮": { level: 1, frequency: "Very Common" },
  "对": { level: 1, frequency: "Very Common" },
  "都": { level: 1, frequency: "Very Common" },
  "很": { level: 1, frequency: "Very Common" },
  "太": { level: 1, frequency: "Very Common" },
  "非常": { level: 1, frequency: "Very Common" },
  "里": { level: 1, frequency: "Very Common" },
  "那": { level: 1, frequency: "Very Common" },

  // HSK 2 - Building blocks (300 words)
  "得": { level: 2, frequency: "Very Common" },
  "给": { level: 2, frequency: "Very Common" },
  "让": { level: 2, frequency: "Very Common" },
  "把": { level: 2, frequency: "Very Common" },
  "被": { level: 2, frequency: "Very Common" },
  "从": { level: 2, frequency: "Very Common" },
  "向": { level: 2, frequency: "Very Common" },
  "比": { level: 2, frequency: "Very Common" },
  "跟": { level: 2, frequency: "Very Common" },
  "着": { level: 2, frequency: "Very Common" },
  "过": { level: 2, frequency: "Very Common" },
  "起来": { level: 2, frequency: "Very Common" },
  "下去": { level: 2, frequency: "Very Common" },
  "起床": { level: 2, frequency: "Common" },
  "睡觉": { level: 2, frequency: "Common" },
  "休息": { level: 2, frequency: "Common" },
  "运动": { level: 2, frequency: "Common" },
  "游泳": { level: 2, frequency: "Common" },
  "跑步": { level: 2, frequency: "Common" },
  "唱歌": { level: 2, frequency: "Common" },
  "跳舞": { level: 2, frequency: "Common" },
  "旅游": { level: 2, frequency: "Common" },
  "准备": { level: 2, frequency: "Common" },
  "开始": { level: 2, frequency: "Common" },
  "结束": { level: 2, frequency: "Common" },
  "完成": { level: 2, frequency: "Common" },
  "帮助": { level: 2, frequency: "Common" },
  "告诉": { level: 2, frequency: "Common" },
  "知道": { level: 2, frequency: "Common" },
  "明白": { level: 2, frequency: "Common" },
  "懂": { level: 2, frequency: "Common" },
  "记得": { level: 2, frequency: "Common" },
  "忘记": { level: 2, frequency: "Common" },
  "希望": { level: 2, frequency: "Common" },
  "觉得": { level: 2, frequency: "Common" },
  "相信": { level: 2, frequency: "Common" },
  "担心": { level: 2, frequency: "Common" },
  "害怕": { level: 2, frequency: "Common" },
  "生气": { level: 2, frequency: "Common" },
  "快乐": { level: 2, frequency: "Common" },
  "幸福": { level: 2, frequency: "Common" },
  "舒服": { level: 2, frequency: "Common" },
  "累": { level: 2, frequency: "Common" },
  "饿": { level: 2, frequency: "Common" },
  "渴": { level: 2, frequency: "Common" },
  "疼": { level: 2, frequency: "Common" },
  "病": { level: 2, frequency: "Common" },
  "感冒": { level: 2, frequency: "Common" },
  "身体": { level: 2, frequency: "Common" },
  "眼睛": { level: 2, frequency: "Common" },
  "耳朵": { level: 2, frequency: "Common" },
  "鼻子": { level: 2, frequency: "Common" },
  "嘴": { level: 2, frequency: "Common" },
  "手": { level: 2, frequency: "Common" },
  "脚": { level: 2, frequency: "Common" },
  "头": { level: 2, frequency: "Common" },
  "脸": { level: 2, frequency: "Common" },
  "头发": { level: 2, frequency: "Common" },
  "颜色": { level: 2, frequency: "Common" },
  "红": { level: 2, frequency: "Common" },
  "黄": { level: 2, frequency: "Common" },
  "蓝": { level: 2, frequency: "Common" },
  "绿": { level: 2, frequency: "Common" },
  "黑": { level: 2, frequency: "Common" },
  "白": { level: 2, frequency: "Common" },
  "春": { level: 2, frequency: "Common" },
  "夏": { level: 2, frequency: "Common" },
  "秋": { level: 2, frequency: "Common" },
  "冬": { level: 2, frequency: "Common" },
  "早上": { level: 2, frequency: "Common" },
  "上午": { level: 2, frequency: "Common" },
  "中午": { level: 2, frequency: "Common" },
  "下午": { level: 2, frequency: "Common" },
  "晚上": { level: 2, frequency: "Common" },
  "快": { level: 2, frequency: "Common" },
  "慢": { level: 2, frequency: "Common" },
  "新": { level: 2, frequency: "Common" },
  "旧": { level: 2, frequency: "Common" },
  "长": { level: 2, frequency: "Common" },
  "短": { level: 2, frequency: "Common" },
  "高": { level: 2, frequency: "Common" },
  "矮": { level: 2, frequency: "Common" },
  "胖": { level: 2, frequency: "Common" },
  "瘦": { level: 2, frequency: "Common" },
  "年轻": { level: 2, frequency: "Common" },
  "老": { level: 2, frequency: "Common" },
  "聪明": { level: 2, frequency: "Common" },
  "努力": { level: 2, frequency: "Common" },
  "认真": { level: 2, frequency: "Common" },
  "容易": { level: 2, frequency: "Common" },
  "难": { level: 2, frequency: "Common" },
  "简单": { level: 2, frequency: "Common" },
  "重要": { level: 2, frequency: "Common" },
  "特别": { level: 2, frequency: "Common" },
  "有意思": { level: 2, frequency: "Common" },
  "方便": { level: 2, frequency: "Common" },
  "干净": { level: 2, frequency: "Common" },
  "安静": { level: 2, frequency: "Common" },
  "热闹": { level: 2, frequency: "Common" },
  "清楚": { level: 2, frequency: "Common" },

  // HSK 3 - Intermediate (600 words) - Sample of most common
  "而": { level: 3, frequency: "Common" },
  "或": { level: 3, frequency: "Common" },
  "但": { level: 3, frequency: "Common" },
  "因为": { level: 3, frequency: "Common" },
  "所以": { level: 3, frequency: "Common" },
  "虽然": { level: 3, frequency: "Common" },
  "但是": { level: 3, frequency: "Common" },
  "如果": { level: 3, frequency: "Common" },
  "那么": { level: 3, frequency: "Common" },
  "除了": { level: 3, frequency: "Common" },
  "只要": { level: 3, frequency: "Common" },
  "只有": { level: 3, frequency: "Common" },
  "不但": { level: 3, frequency: "Common" },
  "而且": { level: 3, frequency: "Common" },
  "接受": { level: 3, frequency: "Common" },
  "拒绝": { level: 3, frequency: "Common" },
  "同意": { level: 3, frequency: "Common" },
  "反对": { level: 3, frequency: "Common" },
  "支持": { level: 3, frequency: "Common" },
  "批评": { level: 3, frequency: "Common" },
  "表扬": { level: 3, frequency: "Common" },
  "鼓励": { level: 3, frequency: "Common" },
  "建议": { level: 3, frequency: "Common" },
  "要求": { level: 3, frequency: "Common" },
  "允许": { level: 3, frequency: "Common" },
  "禁止": { level: 3, frequency: "Common" },
  "保护": { level: 3, frequency: "Common" },
  "创造": { level: 3, frequency: "Common" },
  "发明": { level: 3, frequency: "Common" },
  "发现": { level: 3, frequency: "Common" },
  "研究": { level: 3, frequency: "Common" },
  "调查": { level: 3, frequency: "Common" },
  "分析": { level: 3, frequency: "Common" },
  "比较": { level: 3, frequency: "Common" },
  "判断": { level: 3, frequency: "Common" },
  "决定": { level: 3, frequency: "Common" },
  "选择": { level: 3, frequency: "Common" },
  "考虑": { level: 3, frequency: "Common" },
  "思考": { level: 3, frequency: "Common" },
  "想象": { level: 3, frequency: "Common" },
  "证明": { level: 3, frequency: "Common" },
  "解释": { level: 3, frequency: "Common" },
  "说明": { level: 3, frequency: "Common" },
  "介绍": { level: 3, frequency: "Common" },
  "描述": { level: 3, frequency: "Common" },
  "表达": { level: 3, frequency: "Common" },
  "表示": { level: 3, frequency: "Common" },
  "表现": { level: 3, frequency: "Common" },
  "显示": { level: 3, frequency: "Common" },
  "反映": { level: 3, frequency: "Common" },
  "代表": { level: 3, frequency: "Common" },
  "包括": { level: 3, frequency: "Common" },
  "组成": { level: 3, frequency: "Common" },
  "形成": { level: 3, frequency: "Common" },
  "产生": { level: 3, frequency: "Common" },
  "发生": { level: 3, frequency: "Common" },
  "出现": { level: 3, frequency: "Common" },
  "存在": { level: 3, frequency: "Common" },
  "消失": { level: 3, frequency: "Common" },
  "增加": { level: 3, frequency: "Common" },
  "减少": { level: 3, frequency: "Common" },
  "提高": { level: 3, frequency: "Common" },
  "降低": { level: 3, frequency: "Common" },
  "改变": { level: 3, frequency: "Common" },
  "变化": { level: 3, frequency: "Common" },
  "发展": { level: 3, frequency: "Common" },
  "进步": { level: 3, frequency: "Common" },
  "成功": { level: 3, frequency: "Common" },
  "失败": { level: 3, frequency: "Common" },
  "得到": { level: 3, frequency: "Common" },
  "失去": { level: 3, frequency: "Common" },
  "获得": { level: 3, frequency: "Common" },
  "达到": { level: 3, frequency: "Common" },
  "实现": { level: 3, frequency: "Common" },
  "继续": { level: 3, frequency: "Common" },
  "停止": { level: 3, frequency: "Common" },
  "坚持": { level: 3, frequency: "Common" },
  "放弃": { level: 3, frequency: "Common" },
  "保持": { level: 3, frequency: "Common" },
  "维持": { level: 3, frequency: "Common" },
  "保存": { level: 3, frequency: "Common" },
  "节约": { level: 3, frequency: "Common" },
  "浪费": { level: 3, frequency: "Common" },
  "利用": { level: 3, frequency: "Common" },
  "使用": { level: 3, frequency: "Common" },
  "应用": { level: 3, frequency: "Common" },
  "交流": { level: 3, frequency: "Common" },
  "沟通": { level: 3, frequency: "Common" },
  "联系": { level: 3, frequency: "Common" },
  "合作": { level: 3, frequency: "Common" },
  "组织": { level: 3, frequency: "Common" },
  "安排": { level: 3, frequency: "Common" },
  "计划": { level: 3, frequency: "Common" },
  "打算": { level: 3, frequency: "Common" },
  "估计": { level: 3, frequency: "Common" },
  "期待": { level: 3, frequency: "Common" },
  "追求": { level: 3, frequency: "Common" },
  "寻找": { level: 3, frequency: "Common" },
  "探索": { level: 3, frequency: "Common" },
  "讨论": { level: 3, frequency: "Common" },
  "争论": { level: 3, frequency: "Common" },
  "谈判": { level: 3, frequency: "Common" },
  "商量": { level: 3, frequency: "Common" },
  "协商": { level: 3, frequency: "Common" },
  "交谈": { level: 3, frequency: "Common" },
  "聊天": { level: 3, frequency: "Common" },
  "声明": { level: 3, frequency: "Common" },
  "宣布": { level: 3, frequency: "Common" },
  "通知": { level: 3, frequency: "Common" },
  "报告": { level: 3, frequency: "Common" },
  "新闻": { level: 3, frequency: "Common" },
  "消息": { level: 3, frequency: "Common" },
  "信息": { level: 3, frequency: "Common" },
  "资料": { level: 3, frequency: "Common" },
  "数据": { level: 3, frequency: "Common" },
  "事实": { level: 3, frequency: "Common" },
  "真相": { level: 3, frequency: "Common" },
  "实际": { level: 3, frequency: "Common" },
  "现实": { level: 3, frequency: "Common" },
  "实践": { level: 3, frequency: "Common" },
  "经验": { level: 3, frequency: "Common" },
  "知识": { level: 3, frequency: "Common" },
  "科学": { level: 3, frequency: "Common" },
  "技术": { level: 3, frequency: "Common" },
  "方法": { level: 3, frequency: "Common" },
  "办法": { level: 3, frequency: "Common" },
  "措施": { level: 3, frequency: "Common" },
  "方式": { level: 3, frequency: "Common" },
  "形式": { level: 3, frequency: "Common" },
  "类型": { level: 3, frequency: "Common" },
  "种类": { level: 3, frequency: "Common" },
  "风格": { level: 3, frequency: "Common" },
  "特点": { level: 3, frequency: "Common" },
  "特色": { level: 3, frequency: "Common" },
  "性质": { level: 3, frequency: "Common" },
  "功能": { level: 3, frequency: "Common" },
  "作用": { level: 3, frequency: "Common" },
  "效果": { level: 3, frequency: "Common" },
  "影响": { level: 3, frequency: "Common" },
  "结果": { level: 3, frequency: "Common" },
  "成果": { level: 3, frequency: "Common" },
  "成就": { level: 3, frequency: "Common" },
  "价值": { level: 3, frequency: "Common" },
  "意义": { level: 3, frequency: "Common" },
};

// For other languages, we'll use a more compact structure
// Spanish, French, German, Japanese, Korean, Arabic databases follow similar patterns
// but are kept smaller for initial implementation

export function getWordLevel(word: string, language: string): { level: number; frequency: string } | null {
  const normalizedLang = language.toLowerCase();
  
  if (normalizedLang === "chinese" || normalizedLang === "mandarin") {
    return chineseHSKDatabase[word] || null;
  }
  
  // For other languages, return null for now (can be extended)
  return null;
}

export function getLevelName(level: number, language: string): string {
  const normalizedLang = language.toLowerCase();
  
  switch (normalizedLang) {
    case "chinese":
    case "mandarin":
      return `HSK ${level}`;
    case "spanish":
    case "french":
    case "german":
    case "arabic":
      const cefrLevels = ["A1", "A2", "B1", "B2", "C1", "C2"];
      return cefrLevels[level - 1] || "Unknown";
    case "japanese":
      return `JLPT N${level}`;
    case "korean":
      return `TOPIK ${level}`;
    default:
      return `Level ${level}`;
  }
}

export function getVocabDatabaseSize(language: string): number {
  const normalizedLang = language.toLowerCase();
  
  if (normalizedLang === "chinese" || normalizedLang === "mandarin") {
    return Object.keys(chineseHSKDatabase).length;
  }
  
  return 0;
}
